# Generated by Django 5.2.7 on 2025-10-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category')),
                ('slug', models.SlugField(help_text='Short description of the cut', unique=True)),
                ('description', models.TextField(blank=True, help_text='Krótki opis kategorii, widoczny na stronie kategorii.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy aktywna w sklepie')),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa Produktu')),
                ('description', models.TextField(help_text="Pełny opis produktu i jego 'antystresowych' cech.")),
                ('material', models.CharField(default='Bawełna organiczna', help_text='Główny materiał wykonania bluzy.', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Podstawowa cena sugerowana (warianty mogą mieć inną).', max_digits=6)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Wyróżniony na stronie głównej')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BLK', 'Black'), ('GRY', 'Gray'), ('NVY', 'Navy'), ('WHT', 'White'), ('AUT', 'Warm autumn beige')], default='BLK', max_length=3, verbose_name='Kolor')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=3, verbose_name='Rozmiar')),
                ('sku', models.CharField(help_text='Unikalny kod magazynowy (Stock Keeping Unit).', max_length=20, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stan Magazynowy')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Jeśli puste, używa ceny podstawowej produktu.', max_digits=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sklep.product', verbose_name='Produkt Matka')),
            ],
            options={
                'verbose_name': 'Wariant Produktu',
                'verbose_name_plural': 'Warianty Produktu',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
