# Generated by Django 5.2.7 on 2026-01-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_position_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
